name: Update AdGuard SRS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh

      - name: Download AdGuard blocklist
        run: |
          curl -fsSL -o blocklist.txt https://github.com/ppfeufer/adguard-filter-list/blob/master/blocklist?raw=true

      - name: Convert to SRS
        run: |
          sing-box rule-set convert --type adguard --output adguard.srs blocklist.txt

      - name: Commit and push updated SRS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add adguard.srs
          if ! git diff --cached --quiet; then
            DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
            git commit -m "Update AdGuard SRS - Updated on $DATE"
            git push origin main
          else
            echo "No changes to commit"
          fi
